### PR TITLE
Remove Chromium SingletonSocket links when launching Zoom

### LINKED ISSUE #445: Can't join meeting from link if Zoom already running
One thing that I didn't include in my brief tests before #443 was merged: joining a Zoom meeting from a link. With Zoom 5.17.5.2543, this seems to be broken if the Zoom client is already running - the 'launch meeting' page opens in Firefox, but Zoom doesn't do anything, and clicking the 'Launch Meeting' button on the page also has no effect.

I can work around it by quitting Zoom (so the tray icon is gone) and then opening the page or clicking the button again.

I'm looking for clues on what's going wrong.

### PR DESCRIPTION
**Pull request by takluyver**
I'm hoping this will fix #445 (and maybe other related issues).

### CODE REVIEW

**Comment by takluyver** [comment]
This now seems to fix joining meetings from links for me. :crossed_fingers:

**Comment by muelli** [comment]
wow, very good work! And including a very nice comment that allows to understand why the statement is there. Thanks!

**Comment by siddhpant** [comment]
Thanks! I can confirm it fixed SSO login problem (#446, #454).

File: zoom.sh [hunk 1]
```diff
@@ -19,4 +19,13 @@ if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
...
 fi
 
+# Chromium's singleton mechanism is active in Zoom but doesn't actually work -
+# it uses a Qt mechanism instead. Chromium in Zoom looks for its socket in folders
+# named with the PID, so normally it won't find it. But PID namespaces mean two
+# Zoom instances can think they have the same PID, and then the second tries
+# to use this mechanism, but it does nothing (and it won't try to use the Qt
+# singleton mechanism). Deleting these sockets bypasses this.
+# https://github.com/flathub/us.zoom.Zoom/issues/445
+rm -f $HOME/.zoom/data/cefcache/*/SingletonSocket
```
Comment (luckispac) [inline zoom.sh:29]: I understand the thinking here and this will work for many cases, but i don't think the hardcoded PATH here would work for all installations.

Comment (luckispac) [reply zoom.sh:29]: I checked on fedora 39 and the path is referenced as: 
`.var/app/us.zoom.Zoom/.zoom/data/...`

Comment (takluyver) [reply zoom.sh:29]: I'm not sure which bit of it can vary - do you see these files being created somewhere else?

Comment (Remu-rin) [reply zoom.sh:29]: It seems that path to `.zoom` directory was changed in https://github.com/flathub/us.zoom.Zoom/pull/455 to be inside `.var` instead of directly in `home`.
After updating from flathub yesterday, I saw that my old login state was not used, and `.var/app/us.zoom.Zoom/` had a new `.zoom` directory in it. Old directory in home also stayed, but after I deleted both `~/.zoom` and `.var/app/us.zoom.Zoom` and launched Zoom again, only `.var` was used for everything including `.zoom`, and it doesn't create `~/.zoom` anymore.
Maybe your `~/.zoom` is also from old versions?

Comment (Remu-rin) [reply zoom.sh:29]: I tested test build in this PR, making sure `~/.zoom` and `.var/app/us.zoom.Zoom` didn't exist before launching, and SSO login from Firefox works now, even though there is no `~/.zoom` in my system. Maybe path gets redirected to `~/.var/app/us.zoom.Zoom/.zoom` by flatpak automatically.
So I'm not sure whether this path for `rm` should be changed.

Comment (muelli) [reply zoom.sh:29]: > Maybe path gets redirected to ~/.var/app/us.zoom.Zoom/.zoom by flatpak automatically.

yeah, that's what `--persist` does.
The `rm` depends on that flag which is a bit more fragile than I'd like, but I not smart enough to come up with a nicer alternative.

Comment (siddhpant) [reply zoom.sh:29]: The code is correct. Once you remember that flatpak sandboxes apps, the behaviour is obvious.

> `xdg-{cache, config, data}` binds mount the paths from host to the per-app sandbox directory. Inside the sandbox `$XDG_CACHE_HOME, $XDG_CONFIG_HOME and $XDG_DATA_HOME` is set to `$HOME/.var/app/<app-id>/{cache, config, data}`. So this permission is not needed unless access to the host directory, bind mounted to `$HOME/.var/app/<app-id>/{cache, config, data}` is desired.
> 
> ~  https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html

Comment (takluyver) [reply zoom.sh:29]: > The rm depends on that flag which is a bit more fragile than I'd like, but I not smart enough to come up with a nicer alternative.

I don't think it does depend on that, because inside the sandbox, Zoom is looking at `~/.zoom`, regardless of anything that the sandbox does to redirect that. The `rm` also runs inside the sandbox, so the hardcoded path should be OK.

What would matter is if there's any config setting or environment variable that can change where Zoom looks for these files within the sandbox. I'm not aware of any, but I also haven't gone looking.
